name: "CI"

on:
  push:
    branches: [ "**" ]
    tags-ignore: [ "**" ]
  pull_request:
  workflow_dispatch:
  schedule: # scheduled to run tests regularly to be notified about changing SimRail backend data
    - cron: '00 1,8,15 * * *'

concurrency:
  cancel-in-progress: true
  group: ci-${{ github.event.pull_request.number || github.ref }}

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and publish

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          java-version: 24
          check-latest: true
          distribution: "zulu"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          add-job-summary: always
          cache-cleanup: on-success
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}

      - name: Execute build and tests
        run: ./gradlew build --stacktrace

      - name: Publish test summary
        if: ${{ always() }}
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: "**/build/test-results/test/TEST-*.xml"
          comment_mode: ${{ github.event_name == 'pull_request' && 'always' || 'off' }}
